server:
  port: 8084
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
spring:
  application:
    name: gateway
zuul:
  routes:
    service0: /service0/**
    service2: /service2/**